### ISSUE TITLE
制作代码管理的框架

### ISSUE THREAD

**Issue by mslxl** [sdufeACM/provlegisto#6]
借助数据库+文件夹的方式组织

或许可以在题目集首选项中进行配置选择，这也要求对文件的管理操作做进一步的抽象

**Comment by mslxl** [comment]
考虑以下设计：

每个问题以单个文件形式存在，每个文件通过头部注释储存以下信息:
| 格式 | 含义 |
|:-|:-|
| `@Provlegisto: {version}` | provlegisto 版本号，用于提供向后兼容 |
| `Title: {name}` | 题目标题 |
| `URL: {url}` | 题目链接 |
| `Limits: {time limits}/{memory limits}` | 时间限制/空间限制 |
| `Contest: {contest file path}` | 描述比赛的 toml 文件路径，可空 |
| `Profile: {profile name}` | 分析，编译，运行，提交代码所使用的 profile 名或 profile URL |


 对于比赛的 toml 文件, 包含以下信息:
| 字段名 | 类型 | 含义 |
|:-|:-|:-|
|name| 字符串| 比赛名 |
|url | 字符串 | 比赛链接 |
|source_dir| 字符串 | 创建文件进行保存时默认的文件夹 |
|problem | Problem 数组 | 该比赛包含的本地代码数组 |


Problem 数组包含信息
| 字段名 | 类型 | 含义 |
|:-|:-|:-|
| index | 字符串 | 题号 |
| name | 字符串 | 题目名 |
| version | 定整数 | 版本号，一个问题可能有多份本地不同的代码（出现重写代码的情况） |
| status | 定整数 | 题目的状态，表示 AC, TLE 等 |
| path | 字符串 | 路径名 |

在界面中以以下形式展示
![image](https://github.com/sdufeACM/provlegisto/assets/11132880/0c2ae19d-df8a-4fa6-a6b4-16ae4f53f8cf)

**Comment by xia0ne** [comment]
我认为 太棒了 简直是来大人转世

**Comment by LionelMessiYoung10** [comment]
> 我认为 太棒了 简直是来大人转世

Why did you say that?   为什么这么说？
